### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by kumavis** [int3/metajs#15]
``` bash
$ make browser
iced -c -I browserify lib/interpreter.coffee
lib/interpreter.coffee:243:11: error: await'ed statements can't act as expressions
          for arg in node.arguments
          ^^^^^^^^^^^^^^^^^^^^^^^^^
make: *** [lib/interpreter.js] Error 1
```

https://github.com/int3/metajs/blob/master/lib/interpreter.coffee#L243-L245

**Comment by omphalos** [comment]
Seems there were breaking changes in IcedCoffeeScript.  Specifying the version (I've been using 1.4.0-c) seems to work.  I updated the README and package.json with this info.
